[world]
name = "Nums"
seed = "nums-v1.0.12"
description = "On chain version of the Number Challenge or Blind Number Challenge game."
website = "https://nums.gg"

[namespace]
default = "NUMS"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
world_address = "0x04aebc039a9beb576533eca4075bacdc037b3c7160de6ed1e2e1a3005129a29e"
account_address = "0x059b1a0c489b635d7c7f43594d187362ddd2dcea6c82db4eef2579fd185b3753"
keystore_path = "./keystore_sepolia.json"

[migration]
order_inits = [
    "NUMS-Setup",
    "NUMS-Minigame",
    "NUMS-Renderer",
    "NUMS-Settings",
    "NUMS-Play",
]
skip_contracts = ["NUMS-MockVRF"]
disable_multicall = true

[writers]
"NUMS" = [
    "NUMS-Setup",
    "NUMS-Minigame",
    "NUMS-Renderer",
    "NUMS-Settings",
    "NUMS-Play",
]

[init_call_args]
"NUMS-Minigame" = [
    "0x02334dc9c950c74c3228e2a343d495ae36f0b4edf06767a679569e9f9de08776", # Denshokan address
]
"NUMS-Play" = [
    "1798758000", # claimable_until
]
"NUMS-Setup" = [
    "0x1",                                                                # nums_address
    "0x0",                                                                # Option::Some
    "0x051fea4450da9d6aee758bdeba88b2f665bcbf549d2c61421aa724e9ac0ced8f", # vrf_address
    "0x0",                                                                # Option::Some
    "0x03eb03b8f2be0ec2aafd186d72f6d8f3dd320dbc89f2b6802bca7465f6ccaa43", # starterpack_address
    "0x059b1a0c489b635d7c7f43594d187362ddd2dcea6c82db4eef2579fd185b3753", # forwarder_address
    "0x059b1a0c489b635d7c7f43594d187362ddd2dcea6c82db4eef2579fd185b3753", # owner_address
    "0x7D0",                                                              # entry_price
]
