[world]
name = "Nums"
seed = "nums-v1.0.27"
description = "On chain version of the Number Challenge or Blind Number Challenge game."
website = "https://nums.gg"

[namespace]
default = "NUMS"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
# world_address = "0x04ab20897d666b7df906bcddbfcad44d2746dbdb6782b2f169692d46a30ea46d"
account_address = "0x059b1a0c489b635d7c7f43594d187362ddd2dcea6c82db4eef2579fd185b3753"
keystore_path = "./keystore_sepolia.json"

[migration]
order_inits = ["NUMS-Setup", "NUMS-Play", "NUMS-Collection"]
skip_contracts = ["NUMS-MockVRF", "NUMS-MockNumsToken", "NUMS-MockStarterpack"]
disable_multicall = true

[writers]
"NUMS" = ["NUMS-Play"]

[owners]
"NUMS" = ["NUMS-Setup", "NUMS-Collection"]

[init_call_args]
"NUMS-Setup" = [
  "0x0",                                                                # Option::Some
  "0x6d97c1eb0ad331837882af3a7a0cd49b4a8f24603f9ca42dfdcdf6ece0ac56d",  # nums_address
  "0x0",                                                                # Option::Some
  "0x051fea4450da9d6aee758bdeba88b2f665bcbf549d2c61421aa724e9ac0ced8f", # vrf_address
  "0x0",                                                                # Option::Some
  "0x03eb03b8f2be0ec2aafd186d72f6d8f3dd320dbc89f2b6802bca7465f6ccaa43", # starterpack_address
  "0x059b1a0c489b635d7c7f43594d187362ddd2dcea6c82db4eef2579fd185b3753", # owner_address
  "0xF423F",                                                            # entry_price: 0.990000 USDC
  "0x6765C793FA10079D0000000",                                          # target_supply - low
  "0x0",                                                                # target_supply - high
]
