[workspace]
members = ["contracts"]
description = "Nums"
homepage = "https://github.com/cartridge-gg/nums"

[workspace.package]
version = "0.0.0"
edition = "2024_07"

[workspace.dependencies]
achievement = { git = "https://github.com/cartridge-gg/arcade", rev = "0d46127" }
starterpack = { git = "https://github.com/cartridge-gg/arcade", rev = "0d46127" }
game_components = { git = "https://github.com/bal7hazar/game-components", rev = "60b4e21" }
graffiti = { git = "https://github.com/bal7hazar/graffiti.git", rev = "e8b0854" }
dojo = { git = "https://github.com/dojoengine/dojo.git", rev = "bc54f5e" }
dojo_cairo_macros = { git = "https://github.com/dojoengine/dojo.git", rev = "bc54f5e" }
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo.git", rev = "bc54f5e" }
openzeppelin = "2.0.0"
alexandria_encoding = "0.6.1"
starknet = "2.13.1"
cairo_test = "2.13.1"

[workspace.tool.fmt]
sort-module-level-items = true

[profile.slot]
[profile.mainnet]
[profile.sepolia]

[tool.scarb]
allow-prebuilt-plugins = ["dojo_cairo_macros"]
