[workspace]
members = ["contracts"]
description = "Nums"
homepage = "https://github.com/cartridge-gg/nums"

[workspace.package]
version = "0.0.0"
edition = "2024_07"

[workspace.dependencies]
achievement = { git = "https://github.com/cartridge-gg/arcade", rev = "e3c5c27" }
starterpack = { git = "https://github.com/cartridge-gg/arcade", rev = "e3c5c27" }
leaderboard = { git = "https://github.com/cartridge-gg/arcade", rev = "e3c5c27" }
collection = { git = "https://github.com/cartridge-gg/arcade", rev = "e3c5c27" }
quest = { git = "https://github.com/cartridge-gg/arcade", rev = "e3c5c27" }
graffiti = { git = "https://github.com/bal7hazar/graffiti.git", rev = "e8b0854" }
ekubo = { git = "https://github.com/EkuboProtocol/starknet-contracts", rev = "cf2e95f" }
dojo = "1.8.0"
dojo_cairo_macros = "1.8.0"
dojo_cairo_test = "1.8.0"
openzeppelin = "2.0.0"
alexandria_encoding = "0.6.1"
starknet = "2.13.1"
cairo_test = "2.13.1"

[workspace.tool.fmt]
sort-module-level-items = true

[profile.slot]
[profile.mainnet]
[profile.sepolia]

[tool.scarb]
allow-prebuilt-plugins = ["dojo_cairo_macros"]
