world_address = "0x0696da94533eb2d45c3ab0a8ddbd536baaba56fc8e0e43c4eedbbe7224d5c78f"
rpc = "https://api.cartridge.gg/x/starknet/sepolia"

[server]
http_cors_origins = ["*"]

[grpc]
optimistic = true

[indexing]
world_block = 0
controllers = true
pending = true
pre_confirmed = true
polling_interval = 250
contracts = []

[sql]
historical = ["NUMS-TrophyProgression", "NUMS-QuestProgression"]

[erc]
metadata_updates = true
