world_address = "0x040009ef1417e3814a99dcb202a1dc81f70ac0c3aee5eb2f22ded39ac36fbbce"
rpc = "https://api.cartridge.gg/x/starknet/sepolia"

[server]
http_cors_origins = ["*"]

[grpc]
optimistic = true

[indexing]
world_block = 0
controllers = true
pending = true
pre_confirmed = true
polling_interval = 250
contracts = []

[sql]
historical = ["NUMS-TrophyProgression", "NUMS-QuestProgression"]

[erc]
metadata_updates = true
