[package]
name = "nums_tokens"
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.13.1"

[dependencies]
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v2.0.0" }
starknet = "2.13.1"

[[target.starknet-contract]]
sierra = true
casm = false
